server:
  port: 4567

spring:
  application:
    name: ServiceLinkLite
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  threads:
    virtual:
      enabled: true

feedback:
  enabled: true
  dingTalk:
    webhook: ""
    secret: ""
  rate-limit:
    enabled: true
    limit-per-minute: 1
